[package]
name = "checkm8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb1-sys = "0.6.4"
rusb = "0.9.3"

